name: codeblock
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/photo/codeblock.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/photo/
    - assets/mp4/